import {GoogleSpreadsheet} from "google-spreadsheet";
import * as dotenv from "dotenv";
dotenv.config();
export class GoogleSheetConfig{
    public doc:GoogleSpreadsheet | undefined;
    constructor(){
        this.init();
    }
    private init=async():Promise<void>=>{
        // Initialize the sheet - doc ID is the long id in the sheets URL
        this.doc=new GoogleSpreadsheet(process.env.ID_SHEET);
        await this.doc.useServiceAccountAuth({
            // env var values are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || "",
            private_key: process.env.GOOGLE_PRIVATE_KEY || "",
          });
        if (this.doc) {
            console.log("Initialize the sheet");
        } else {
            console.log("No sheets");
        }
    }
}